"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Sandwich(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _State:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _StateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Sandwich._State.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        START: Sandwich._State.ValueType  # 0
        NOTHING: Sandwich._State.ValueType  # 1
        BREAD: Sandwich._State.ValueType  # 2
        HAM: Sandwich._State.ValueType  # 3
        LETTUCE: Sandwich._State.ValueType  # 4
        CUCUMBER: Sandwich._State.ValueType  # 5
        HALF: Sandwich._State.ValueType  # 6
        TOMATO: Sandwich._State.ValueType  # 7
        HAM_WRONG: Sandwich._State.ValueType  # 8
        FULL: Sandwich._State.ValueType  # 9
    class State(_State, metaclass=_StateEnumTypeWrapper):
        pass

    START: Sandwich.State.ValueType  # 0
    NOTHING: Sandwich.State.ValueType  # 1
    BREAD: Sandwich.State.ValueType  # 2
    HAM: Sandwich.State.ValueType  # 3
    LETTUCE: Sandwich.State.ValueType  # 4
    CUCUMBER: Sandwich.State.ValueType  # 5
    HALF: Sandwich.State.ValueType  # 6
    TOMATO: Sandwich.State.ValueType  # 7
    HAM_WRONG: Sandwich.State.ValueType  # 8
    FULL: Sandwich.State.ValueType  # 9

    STATE_FIELD_NUMBER: builtins.int
    HOLO_X_FIELD_NUMBER: builtins.int
    HOLO_Y_FIELD_NUMBER: builtins.int
    HOLO_DEPTH_FIELD_NUMBER: builtins.int
    state: global___Sandwich.State.ValueType
    holo_x: builtins.float
    holo_y: builtins.float
    holo_depth: builtins.float
    def __init__(self,
        *,
        state: global___Sandwich.State.ValueType = ...,
        holo_x: builtins.float = ...,
        holo_y: builtins.float = ...,
        holo_depth: builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["holo_depth",b"holo_depth","holo_x",b"holo_x","holo_y",b"holo_y","state",b"state"]) -> None: ...
global___Sandwich = Sandwich

class EngineFields(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    UPDATE_COUNT_FIELD_NUMBER: builtins.int
    SANDWICH_FIELD_NUMBER: builtins.int
    update_count: builtins.int
    @property
    def sandwich(self) -> global___Sandwich: ...
    def __init__(self,
        *,
        update_count: builtins.int = ...,
        sandwich: typing.Optional[global___Sandwich] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["sandwich",b"sandwich","state",b"state"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["sandwich",b"sandwich","state",b"state","update_count",b"update_count"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["state",b"state"]) -> typing.Optional[typing_extensions.Literal["sandwich"]]: ...
global___EngineFields = EngineFields
