# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_state.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app_state.proto',
  package='state',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x61pp_state.proto\x12\x05state\"!\n\x08\x41ppState\x12\x15\n\ruser_progress\x18\x01 \x03(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_APPSTATE = _descriptor.Descriptor(
  name='AppState',
  full_name='state.AppState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_progress', full_name='state.AppState.user_progress', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['AppState'] = _APPSTATE

AppState = _reflection.GeneratedProtocolMessageType('AppState', (_message.Message,), dict(
  DESCRIPTOR = _APPSTATE,
  __module__ = 'app_state_pb2'
  # @@protoc_insertion_point(class_scope:state.AppState)
  ))
_sym_db.RegisterMessage(AppState)


# @@protoc_insertion_point(module_scope)
