"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import gabriel_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class AppState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    USER_PROGRESS_FIELD_NUMBER: builtins.int
    RESULT_WRAPPER_FIELD_NUMBER: builtins.int
    @property
    def user_progress(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def result_wrapper(self) -> gabriel_pb2.ResultWrapper: ...
    def __init__(self,
        *,
        user_progress: typing.Optional[typing.Iterable[typing.Text]] = ...,
        result_wrapper: typing.Optional[gabriel_pb2.ResultWrapper] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["result_wrapper",b"result_wrapper"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["result_wrapper",b"result_wrapper","user_progress",b"user_progress"]) -> None: ...
global___AppState = AppState
